site_name: Transclusion
site_description: Transclusion framework
#site_url: https://lineblock.org/

repo_name: kimjarvis/translusion
repo_url: https://github.com/kimjarvis/translusion

theme:
  name: material
  palette:
    scheme: slate  # This enables dark mode with no toggle

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md


